EXP_NAME: ff_xception_dfdc

DATA:
  name: dfdc
  data_path: /workspace/volume3/sohyun/dfdc_preprocessed
  test_data_path: None
  image_size: 229
  batch_size: 32
  num_workers: 4

MODEL:
  name: Xception
  pretrained: True
  num_classes: 2

LOG_FILENAME: '.log/ff_xception'
CHK_DIR: 'checkpoints/ff/'
WEIGHTS: 'checkpoints/ff/ff_xception_train_iter_1500.pt'