EXP_NAME: all_i3d_supcon_finetune

DATA:
  train_data_name: ff
  multiple: True
  image_size: 224
  batch_size: 64
  num_workers: 4
  type: video
  frames: 32

MODEL:
  name: I3D
  pretrained: True
  weights: 'checkpoints/all_i3d_supcon/1205-1406-20/best.pt'
  num_classes: 2
  freeze: True
  frames: 32

TRAIN:
  epochs: 30
  lr: 0.0001
  momentum: 0.9
  weight_decay: 0.0001
  lr_step_size: 7
  lr_gamma: 0.1
  log_interval: 20
  save_interval: 100
  ckpt_dir: 'checkpoints/all_i3d_supcon_finetune/'
  load_ckpt_dir: None

RETRAIN: false
