EXP_NAME: dfdc_xception_train

DATA:
  name: dfdc
  data_path: /workspace/volume3/sohyun/dfdc_preprocessed
  test_data_path: None
  image_size: 229
  batch_size: 32
  num_workers: 4

MODEL:
  name: Xception
  pretrained: True
  num_classes: 2

TRAIN:
  EPOCH: 15
  lr: 0.001
  momentum: 0.9
  weight_decay: 0.0001
  lr_step_size: 7
  lr_gamma: 0.1
  LOG_INTERVAL: 20
  SAVE_INTERVAL: 100

LOG_FILENAME: '.log/dfdc_xception_pretrain'
CHK_DIR: 'checkpoints/dfdc/'