EXP_NAME: ff_xception_train

DATA:
  train_data_name: ff
  train_data_path: /workspace/ssd1/users/sumin/datasets/ff
  test_data_path: None
  image_size: 229
  batch_size: 32
  num_workers: 4

MODEL:
  name: Xception
  pretrained: True
  num_classes: 2

TRAIN:
  epochs: 15
  lr: 0.001
  momentum: 0.9
  weight_decay: 0.0001
  lr_step_size: 7
  lr_gamma: 0.1
  log_interval: 20
  save_interval: 100
  ckpt_dir: 'checkpoints/ff/'
  load_ckpt_dir: None

LOG_FILENAME: '.log/ff_xception'
RETRAIN: false
