EXP_NAME: ff_xception_baseline

DATA:
  train_data_name: ff
  image_size: 229
  batch_size: 256
  num_workers: 4

MODEL:
  name: Xception
  pretrained: True
  num_classes: 2

TRAIN:
  epochs: 30
  lr: 0.001
  momentum: 0.9
  weight_decay: 0.0001
  lr_step_size: 7
  lr_gamma: 0.1
  log_interval: 20
  save_interval: 100
  ckpt_dir: 'checkpoints/ff_xception_baseline/'
  load_ckpt_dir: None

LOG_FILENAME: '.log/ff_xception_baseline'
RETRAIN: false
