EXP_NAME: ff_xception_train

DATA:
  name: FF
  data_path: /workspace/ssd1/users/sumin/result/h5_result/ff/use_own_bbox
  image_size: 229
  batch_size: 32
  num_workers: 4

MODEL:
  name: Xception
  pretrained: True
  num_classes: 2

TRAIN:
  EPOCH: 15
  lr: 0.001
  momentum: 0.9
  weight_decay: 0.0001
  lr_step_size: 7
  lr_gamma: 0.1
  LOG_INTERVAL: 10
  SAVE_INTERVAL: 100

LOG_FILENAME: '.log/ff_xception'
CHK_DIR: 'checkpoints/ff/'