EXP_NAME: ff_i3d

DATA:
  train_data_name: ff
  image_size: 224
  batch_size: 16
  num_workers: 4
  type: video
  frames: 32

MODEL:
  name: I3D
  pretrained: True
  num_classes: 2
  frames: 32

TRAIN:
  epochs: 15
  lr: 0.0001
  momentum: 0.9
  weight_decay: 0.0001
  lr_step_size: 7
  lr_gamma: 0.1
  log_interval: 20
  save_interval: 100
  ckpt_dir: 'checkpoints/ff_i3d/'
  load_ckpt_dir: None